In [1]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [2]:
Data1={'Name':['Ramesh','Suresh','Ramesh',None],
       'Age':[None,22,25,27],
       'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data1)
df1

Name   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Ramesh  25.0  None
3    None  27.0   Hyd

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [4]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [5]:
df.isnull

<bound method DataFrame.isnull of     Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd>

**fillna**

In [9]:
df.fillna(30)  # Not recomended

Names   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0    30
3      30  27.0   Hyd

In [10]:
df1.fillna(30)  

Name   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0  Pune
2  Ramesh  25.0    30
3      30  27.0   Hyd

In [11]:
df.fillna('Hyd')

Names   Age  City
0  Ramesh   Hyd  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     Hyd  27.0   Hyd

df['age'].fillna(30) # error

- The above one is we are filling randomly

- All the columns are filled with random number

- It is not a good approach because in a data we have different data types

**What is the difference between np.nan and None**

In [14]:
np.nan+5

nan

In [16]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [17]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [18]:
arr1

array([ 1.,  2., nan,  3.])

In [19]:
arr2

array([1, 2, None, 3], dtype=object)

In [20]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [21]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represents **float type**

- None represents **Object type**

- if data operations related to Maths then nan format is better

**Fill the Value based on column**

- Whenever we are using methods no need to provide values

In [24]:
# df.fillna()
df['Names'].fillna('Manish')

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Names, dtype: object

In [26]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

- pad

- bfill

- ffill

- backfill

In [33]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')       
# upper value asses lower

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [39]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)  

Names     Age  City
0  Ramesh  Ramesh  Pune
1  Suresh    22.0  Pune
2  Satish    25.0  25.0
3     NaN    27.0   Hyd

In [34]:
df.fillna(method='bfill')
# l

Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [36]:
df.fillna(method='ffill')

Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [38]:
df.fillna(method='backfill')

Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

- Mean-Median-Mode

- we can use mean median and mode also

- For Numerical columns use mean and Median

     - if Data outliers are there use **Median**
 
- For categorical columns use **Mode**

In [41]:
# first calculate median
# Then fill with median
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [42]:
age_median

25.0

In [45]:
round(df['Age']).median

<bound method Series.median of 0     NaN
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64>

In [46]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

In [ ]:
mode=df[

**KNN Imputer**

- K-Nearest Neighbours 

- Where k=hyper parameter which means the user can change

- Idea : Instead of taking all the samples averages

    - First fix the neighbours number i.e.k

    - Then find the neighbours using distance metric
 
    - Then take the average of those samepls to fill the missing value


In [12]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [14]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)
   

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [17]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,
                    weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [18]:
import numpy as np
from sklearn.impute import KNNIputer
X=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]

imputer=KNNImputer

ImportError: cannot import name 'KNNIputer' from 'sklearn.impute' (C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\impute\__init__.py)